name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger the workflow when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository's code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'  # Specify the Python version if necessary

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Install the dependencies

    - name: Setup SSH Key and Test Variables
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ls -la
        echo "PRIVATE KEY CONTENT:"
        cat private_key.pem
        echo "SERVER IP:"
        echo "$SERVER_IP"
        echo "SERVER USER:"
        echo "$SERVER_USER"



    - name: Deploy over SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "bash -s" << 'EOF'
          cd /root/Api-pdf-Downloader-
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF



